---
security_selinux_policy: targeted
security_selinux_state: enforcing

security_sysctl_parameters:
  - { key: 'net.ipv4.ip_forward', value: '0' }
  - { key: 'net.ipv4.conf.all.send_redirects', value: '0' }
  - { key: 'net.ipv4.conf.default.send_redirects', value: '0' }
  - { key: 'net.ipv4.conf.all.accept_redirects', value: '0' }
  - { key: 'net.ipv4.conf.default.accept_redirects', value: '0' }
  - { key: 'net.ipv4.conf.all.accept_source_route', value: '0' }
  - { key: 'net.ipv4.conf.default.accept_source_route', value: '0' }
  - { key: 'net.ipv4.conf.all.log_martians', value: '1' }
  - { key: 'net.ipv4.conf.default.log_martians', value: '1' }
  - { key: 'net.ipv4.icmp_echo_ignore_broadcasts', value: '1' }
  - { key: 'net.ipv4.icmp_ignore_bogus_error_responses', value: '1' }
  - { key: 'net.ipv4.tcp_syncookies', value: '1' }
  - { key: 'kernel.dmesg_restrict', value: '1' }
  - { key: 'kernel.kptr_restrict', value: '2' }
  - { key: 'net.ipv6.conf.all.forwarding', value: '0' }
  - { key: 'net.ipv6.conf.default.forwarding', value: '0' }
  - { key: 'net.ipv6.conf.all.accept_redirects', value: '0' }
  - { key: 'net.ipv6.conf.default.accept_redirects', value: '0' }
  - { key: 'net.ipv6.conf.all.accept_source_route', value: '0' }
  - { key: 'net.ipv6.conf.default.accept_source_route', value: '0' }
  - { key: 'net.ipv6.conf.all.accept_ra', value: '0' }
  - { key: 'net.ipv6.conf.default.accept_ra', value: '0' }
