---
# Secrets : group_vars/all/vault.yml (vps_ip, main_user, ssh_key_name, ssh_port, etc.)
ansible_host: "{{ vps_ip }}"
ssh_key_path: "~/.ssh/{{ ssh_key_name }}"
ssh_pub_key_path: "~/.ssh/{{ ssh_key_name }}.pub"
ansible_user: "{{ main_user }}"
ansible_ssh_private_key_file: "~/.ssh/{{ ssh_key_name }}"
ansible_port: "{{ ssh_port }}"
