---
fail2ban_backend: systemd
fail2ban_banaction: firewallcmd-ipset
fail2ban_bantime: 3600
fail2ban_findtime: 10m
fail2ban_maxretry: 3
fail2ban_recidive_enabled: true
fail2ban_recidive_bantime: -1
fail2ban_recidive_findtime: 1d
fail2ban_recidive_maxretry: 5
